"use client";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/Page";
import { api } from "@/lib/api";
import type { ImportRecord, Institution } from "@/lib/types";

const fields=[
  ["date_column","Transaction date",true],["post_date_column","Posted date",false],["description_column","Description",true],["merchant_column","Merchant",false],["amount_column","Amount",true],["debit_column","Debit",false],["credit_column","Credit",false],["category_column","Provider category",false],["transaction_id_column","Transaction ID",false],["notes_column","Notes",false],["card_number_column","Card number",false],["card_last_four_column","Card last four",false],["cardholder_name_column","Cardholder / authorized user",false],["account_suffix_column","Account suffix / source identifier",false],
] as const;
export default function MappingPage(){
  const {id}=useParams<{id:string}>();const router=useRouter();const [item,setItem]=useState<ImportRecord|null>(null);const [institutions,setInstitutions]=useState<Institution[]>([]);const [institutionId,setInstitutionId]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [force,setForce]=useState(false);
  useEffect(()=>{Promise.all([api<ImportRecord>(`/imports/${id}`),api<Institution[]>("/institutions")]).then(([record,rows])=>{setItem(record);setInstitutions(rows);setInstitutionId(record.institution_id||"")}).catch(e=>setError(e.message));},[id]);
  const proposed=useMemo(()=>item?.proposed_mapping||{},[item]);
  async function addInstitution(){const name=window.prompt("Institution name");if(!name?.trim())return;try{const created=await api<Institution>("/institutions",{method:"POST",body:JSON.stringify({display_name:name})});setInstitutions(current=>[...current.filter(row=>row.id!==created.id),created].sort((a,b)=>a.display_name.localeCompare(b.display_name)));setInstitutionId(created.id)}catch(e){setError(e instanceof Error?e.message:"Could not add institution")}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);const payload:Record<string,unknown>={institution_id:institutionId,account_type:f.get("account_type"),mapping_name:f.get("mapping_name"),amount_behavior:f.get("amount_behavior")};for(const [key] of fields)payload[key]=f.get(key)||null;try{const mapping=await api<{id:string}>(`/imports/${id}/mapping`,{method:"POST",body:JSON.stringify(payload)});await api(`/imports/${id}/normalize?mapping_id=${mapping.id}&force_duplicate_file=${force}`,{method:"POST"});router.push(`/imports/${id}/review`);}catch(e){setError(e instanceof Error?e.message:"Could not normalize file");setBusy(false)}}
  if(!item)return <><PageHeader title="Inspecting CSV…"/>{error&&<div className="notice notice-error">{error}</div>}</>;
  const sample=item.sample_rows?.[0]||{};
  return <><div className="steps"><div className="step done"/><div className="step active"/><div className="step"/></div><PageHeader eyebrow="Step 2 of 3" title="Confirm the column mapping" description="We proposed a mapping from headers and sample values. Review it before any draft transactions are created."/>
    {item.is_duplicate_file&&<div className="notice notice-warn"><strong>This exact file was uploaded before.</strong> Importing is blocked by default. <label style={{marginLeft:8}}><input type="checkbox" checked={force} onChange={e=>setForce(e.target.checked)}/> Continue anyway</label></div>}{error&&<div className="notice notice-error">{error}</div>}
    <form onSubmit={submit}><div className="card card-pad"><div className="form-grid"><div className="field full"><label>Financial institution</label><div className="institution-picker"><select className="select" name="institution_id" value={institutionId} onChange={e=>setInstitutionId(e.target.value)} required><option value="">Choose an institution</option>{institutions.filter(row=>row.is_active).map(row=><option key={row.id} value={row.id}>{row.display_name}</option>)}</select><button type="button" className="button" onClick={addInstitution}>Add institution</button></div></div><div className="field"><label>Account type</label><select className="select" name="account_type" defaultValue={item.account_type||"other"}><option value="checking">Checking</option><option value="savings">Savings</option><option value="credit_card">Credit card</option><option value="cash">Cash</option><option value="other">Other</option></select></div><div className="field"><label>Mapping name</label><input className="input" name="mapping_name" defaultValue={`${item.institution_name||"Custom"} CSV`} required/></div><div className="field"><label>Amount behavior</label><select className="select" name="amount_behavior" defaultValue={proposed.amount_behavior||"signed_amount"}><option value="signed_amount">Signed amount (positive inflow)</option><option value="charges_positive">Charges are positive</option><option value="charges_negative">Charges are negative</option><option value="debit_credit_columns">Separate debit / credit columns</option><option value="credits_positive">Credits are positive</option><option value="credits_negative">Credits are negative</option></select></div></div></div>
    <div className="section-title"><div><h2>CSV columns</h2><p>{item.headers?.length} headers · showing the first row as a sample</p></div></div><div className="card"><div className="mapping-row header"><span>App field</span><span>CSV column</span><span>Sample value</span><span>Detected</span></div>{fields.map(([key,label,required])=><div className="mapping-row" key={key}><strong>{label}{required&&" *"}</strong><select className="select" name={key} defaultValue={proposed[key]||""}><option value="">Not mapped</option>{item.headers?.map(header=><option key={header} value={header}>{header}</option>)}</select><span className="muted">{sample[proposed[key]||""]||"—"}</span><span className="badge badge-accent">{proposed[key]?"Auto":"Manual"}</span></div>)}</div><div className="form-actions"><button type="button" className="button" onClick={()=>router.push("/imports")}>Save for later</button><button className="button button-primary" disabled={busy||(item.is_duplicate_file&&!force)}>{busy?"Creating drafts…":"Save mapping & review"}</button></div></form>
  </>;
}
