"use client";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/Page";
import { api, money } from "@/lib/api";
import type { Account, Category, Instrument } from "@/lib/types";

const COLORS = ["#176b4d", "#e0b25a", "#527c9e", "#aa6b57", "#7b6ca8", "#81a36c", "#ce8e45", "#477d72"];
interface Summary { spending: string; income: string; net_cash_flow: string; recurring_spend: string; uncategorized_count: number; review_needed_count: number; }

export default function DashboardPage() {
  const [summary, setSummary] = useState<Summary | null>(null); const [breakdown, setBreakdown] = useState<{category:string; amount:string}[]>([]); const [trends, setTrends] = useState<{month:string; income:string; spending:string}[]>([]);const [recurring,setRecurring]=useState<{merchant:string;amount:string}[]>([]);const [accountSpend,setAccountSpend]=useState<{account:string;amount:string}[]>([]);const [instrumentSpend,setInstrumentSpend]=useState<{instrument:string;amount:string}[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [instruments,setInstruments]=useState<Instrument[]>([]);const [taxonomy,setTaxonomy]=useState<Category[]>([]);const [filters,setFilters]=useState({account_id:"",account_instrument_id:"",category_id:"",subcategory_id:"",start_date:"",end_date:""});
  const params = useMemo(() => {const p=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>value&&p.set(key,value));return p.toString()?`?${p}`:""}, [filters]);
  useEffect(() => { Promise.all([api<Account[]>("/accounts"),api<Category[]>("/categories")]).then(([a,c])=>{setAccounts(a);setTaxonomy(c)}); }, []);
  useEffect(()=>{if(!filters.account_id){setInstruments([]);return}api<Instrument[]>(`/accounts/${filters.account_id}/instruments`).then(setInstruments)},[filters.account_id]);
  useEffect(() => { Promise.all([api<Summary>(`/dashboard/summary${params}`), api<{category:string;amount:string}[]>(`/dashboard/category-breakdown${params}`), api<{month:string;income:string;spending:string}[]>(`/dashboard/monthly-trends${filters.account_id?`?account_id=${filters.account_id}`:""}`),api<{merchant:string;amount:string}[]>(`/dashboard/recurring${params}`),api<{account:string;amount:string}[]>(`/dashboard/account-summary${params}`),filters.account_id?api<{instrument:string;amount:string}[]>(`/dashboard/instrument-summary?account_id=${filters.account_id}${filters.start_date?`&start_date=${filters.start_date}`:""}${filters.end_date?`&end_date=${filters.end_date}`:""}`):Promise.resolve([])]).then(([a,b,c,d,e,f]) => { setSummary(a); setBreakdown(b); setTrends(c);setRecurring(d);setAccountSpend(e);setInstrumentSpend(f); }); }, [params,filters.account_id,filters.start_date,filters.end_date]);
  function set(name:string,value:string){setFilters(current=>({...current,[name]:value,...(name==="account_id"?{account_instrument_id:""}:{}) ,...(name==="category_id"?{subcategory_id:""}:{})}))}
  const cards = [
    ["Total spending", money(summary?.spending), "Expenses only; transfers excluded"], ["Total income", money(summary?.income), "Income inflows this month"], ["Net cash flow", money(summary?.net_cash_flow), "Income minus spending"],
    ["Recurring spend", money(summary?.recurring_spend), "Marked recurring expenses"], ["Uncategorized", String(summary?.uncategorized_count ?? "—"), "Transactions to organize"], ["Needs review", String(summary?.review_needed_count ?? "—"), "Draft transactions waiting"],
  ];
  return <><PageHeader eyebrow="Overview" title="Your month at a glance" description="Calendar-month activity across your accounts, with transfers and card payments kept out of spending." />
    <div className="toolbar"><div className="field"><label>From</label><input className="input" type="date" value={filters.start_date} onChange={e=>set("start_date",e.target.value)}/></div><div className="field"><label>To</label><input className="input" type="date" value={filters.end_date} onChange={e=>set("end_date",e.target.value)}/></div><div className="field"><label>Account</label><select className="select" value={filters.account_id} onChange={(e) => set("account_id",e.target.value)}><option value="">All accounts</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Card/profile</label><select className="select" value={filters.account_instrument_id} onChange={e=>set("account_instrument_id",e.target.value)} disabled={!filters.account_id}><option value="">All profiles</option>{instruments.map(item=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select></div><div className="field"><label>Category</label><select className="select" value={filters.category_id} onChange={e=>set("category_id",e.target.value)}><option value="">All categories</option>{taxonomy.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Subcategory</label><select className="select" value={filters.subcategory_id} onChange={e=>set("subcategory_id",e.target.value)} disabled={!filters.category_id}><option value="">All subcategories</option>{taxonomy.find(item=>item.id===filters.category_id)?.subcategories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div></div>
    <div className="grid grid-6">{cards.map(([label,value,note]) => <div className="card summary-card" key={label}><small>{label}</small><strong>{value}</strong><span className="delta">{note}</span></div>)}</div>
    <div className="grid grid-2"><div><div className="section-title"><div><h2>Spending mix</h2><p>Expense totals by category</p></div></div><div className="card chart-card"><div className="chart-wrap"><ResponsiveContainer><PieChart><Pie data={breakdown} dataKey="amount" nameKey="category" innerRadius={65} outerRadius={105} paddingAngle={2}>{breakdown.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip formatter={(value) => money(String(value))} /><Legend /></PieChart></ResponsiveContainer></div></div></div>
    <div><div className="section-title"><div><h2>Income vs expenses</h2><p>Trailing 12 calendar months</p></div></div><div className="card chart-card"><div className="chart-wrap"><ResponsiveContainer><BarChart data={trends}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" tickFormatter={(v) => new Date(v).toLocaleDateString("en-US", {month:"short", timeZone:"UTC"})} /><YAxis tickFormatter={(v) => `$${Math.round(v/1000)}k`} /><Tooltip formatter={(value) => money(String(value))} /><Legend /><Bar dataKey="income" fill="#176b4d" radius={[4,4,0,0]} /><Bar dataKey="spending" fill="#e0b25a" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div></div></div></div>
    <div className="section-title"><div><h2>Monthly spending trend</h2><p>Only outflow expenses that count as spending</p></div></div><div className="card chart-card"><div className="chart-wrap"><ResponsiveContainer><AreaChart data={trends}><defs><linearGradient id="spend" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#176b4d" stopOpacity={.28}/><stop offset="95%" stopColor="#176b4d" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tickFormatter={(v) => new Date(v).toLocaleDateString("en-US", {month:"short", timeZone:"UTC"})}/><YAxis/><Tooltip formatter={(value) => money(String(value))}/><Area type="monotone" dataKey="spending" stroke="#176b4d" fill="url(#spend)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
    <div className="grid grid-2"><div><div className="section-title"><div><h2>Recurring by merchant</h2><p>Approved or manually marked expense activity</p></div></div><div className="card chart-card"><div className="chart-wrap"><ResponsiveContainer><BarChart data={recurring} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="merchant" width={110}/><Tooltip formatter={(value)=>money(String(value))}/><Bar dataKey="amount" fill="#527c9e" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></div></div><div><div className="section-title"><div><h2>{filters.account_id?"Spending by card/profile":"Spending by account"}</h2><p>Attribution within the active view</p></div></div><div className="card chart-card"><div className="chart-wrap"><ResponsiveContainer><BarChart data={filters.account_id?instrumentSpend:accountSpend} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey={filters.account_id?"instrument":"account"} width={130}/><Tooltip formatter={(value)=>money(String(value))}/><Bar dataKey="amount" fill="#e0b25a" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></div></div></div>
  </>;
}
