"use client";
import { useEffect, useState } from "react";
import { Badge, EmptyState, PageHeader } from "@/components/Page";
import { api, money, shortDate } from "@/lib/api";

interface Series{id:string;merchant_name:string;expected_amount:string;amount_variability:string;cadence:string;status:string;first_seen_date:string;last_seen_date:string;next_expected_date?:string}
export default function RecurringPage(){
 const [items,setItems]=useState<Series[]>([]);const [total,setTotal]=useState(0);const [tab,setTab]=useState("suggested");const [error,setError]=useState("");
 async function load(){try{await api<Series[]>("/recurring/suggestions");const result=await api<{items:Series[];monthly_total:number}>("/recurring");setItems(result.items);setTotal(result.monthly_total)}catch(e){setError(e instanceof Error?e.message:"Could not load")}}useEffect(()=>{load()},[]);
 async function action(id:string,verb:"approve"|"reject"){await api(`/recurring/${id}/${verb}`,{method:"POST"});await load()}
 async function createManual(){const merchant_name=window.prompt("Merchant name");if(!merchant_name)return;const expected=window.prompt("Expected amount per occurrence");if(!expected||Number(expected)<=0)return;const cadence=window.prompt("Cadence: weekly, monthly, quarterly, annual, or irregular","monthly");if(!cadence||!["weekly","monthly","quarterly","annual","irregular"].includes(cadence))return;const today=new Date().toISOString().slice(0,10);await api("/recurring/manual",{method:"POST",body:JSON.stringify({merchant_name,expected_amount:expected,amount_variability:0,cadence,status:"approved",first_seen_date:today,last_seen_date:today})});await load()}
 async function edit(item:Series){const merchant_name=window.prompt("Merchant name",item.merchant_name);if(!merchant_name)return;const expected_amount=window.prompt("Expected amount",item.expected_amount);if(!expected_amount)return;await api(`/recurring/${item.id}`,{method:"PATCH",body:JSON.stringify({merchant_name,expected_amount})});await load()}
 async function deactivate(item:Series){await api(`/recurring/${item.id}`,{method:"PATCH",body:JSON.stringify({status:"inactive"})});await load()}
 const visible=items.filter(x=>x.status===tab);
 return <><PageHeader eyebrow="Predictable spending" title="Recurring charges" description="Suggestions require your approval. Transfers and card payments are never treated as subscriptions." actions={<button className="button button-primary" onClick={createManual}>Mark recurring manually</button>}/><div className="grid grid-3"><div className="card summary-card"><small>Approved monthly total</small><strong>{money(total)}</strong><span className="delta">Cadences normalized to a month</span></div><div className="card summary-card"><small>Waiting for review</small><strong>{items.filter(x=>x.status==="suggested").length}</strong><span className="delta">Suggested from repeated activity</span></div><div className="card summary-card"><small>Largest approved</small><strong>{money(Math.max(0,...items.filter(x=>x.status==="approved").map(x=>Number(x.expected_amount))))}</strong><span className="delta">Expected per occurrence</span></div></div>
 <div className="section-title"><div><h2>Series</h2><p>Approve, reject, or revisit detected patterns</p></div><div className="page-actions">{["suggested","approved","rejected","inactive"].map(x=><button key={x} className={`button ${tab===x?"button-primary":""}`} onClick={()=>setTab(x)}>{x}</button>)}</div></div>{error&&<div className="notice notice-error">{error}</div>}<div className="card table-card">{!visible.length?<EmptyState title={`No ${tab} recurring charges`} body="Suggestions appear after at least three similar expenses with a recognizable cadence."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Merchant</th><th>Expected amount</th><th>Cadence</th><th>History</th><th>Next expected</th><th>Actions</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><strong>{x.merchant_name}</strong><div className="muted">± {money(x.amount_variability)}</div></td><td className="amount">{money(x.expected_amount)}</td><td><Badge tone="accent">{x.cadence}</Badge></td><td>{shortDate(x.first_seen_date)} — {shortDate(x.last_seen_date)}</td><td>{shortDate(x.next_expected_date)}</td><td>{x.status==="suggested"?<div className="page-actions"><button className="button button-primary" onClick={()=>action(x.id,"approve")}>Approve</button><button className="button" onClick={()=>action(x.id,"reject")}>Reject</button></div>:<div className="page-actions"><Badge tone={x.status==="approved"?"good":"neutral"}>{x.status}</Badge><button className="button" onClick={()=>edit(x)}>Edit</button>{x.status!=="inactive"&&<button className="button" onClick={()=>deactivate(x)}>Inactive</button>}</div>}</td></tr>)}</tbody></table></div>}</div>
 </>;
}
