"use client";
import { useEffect, useMemo, useState } from "react";
import { Download, Search } from "lucide-react";
import { Badge, EmptyState, PageHeader } from "@/components/Page";
import { API_BASE, api, money, shortDate } from "@/lib/api";
import type { Account, Category, Transaction } from "@/lib/types";

export default function TransactionsPage(){
 const [rows,setRows]=useState<Transaction[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [filters,setFilters]=useState({search:"",account_id:"",category_id:"",transaction_type:"",start_date:"",end_date:""});const [error,setError]=useState("");
 const query=useMemo(()=>{const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));return p.toString()},[filters]);
 useEffect(()=>{Promise.all([api<Transaction[]>(`/transactions?${query}`),api<Account[]>("/accounts"),api<Category[]>("/categories")]).then(([t,a,c])=>{setRows(t);setAccounts(a);setCategories(c)}).catch(e=>setError(e.message));},[query]);
 async function change(row:Transaction,changes:Record<string,unknown>){setRows(rs=>rs.map(x=>x.id===row.id?{...x,...changes} as Transaction:x));try{await api(`/transactions/${row.id}`,{method:"PATCH",body:JSON.stringify(changes)})}catch(e){setError(e instanceof Error?e.message:"Could not save")}}
 function set(name:string,value:string){setFilters(f=>({...f,[name]:value}))}
 return <><PageHeader eyebrow="Ledger" title="Transactions" description="Search, filter, correct, and export normalized confirmed transactions." actions={<a className="button" href={`${API_BASE}/transactions/export?${query}`}><Download size={16}/>Export CSV</a>}/>{error&&<div className="notice notice-error">{error}</div>}
 <div className="toolbar"><div className="field grow"><label>Search</label><div style={{position:"relative"}}><Search size={16} style={{position:"absolute",left:11,top:12,color:"#758078"}}/><input className="input" style={{paddingLeft:35}} value={filters.search} onChange={e=>set("search",e.target.value)} placeholder="Merchant or description"/></div></div><div className="field"><label>From</label><input className="input" type="date" value={filters.start_date} onChange={e=>set("start_date",e.target.value)}/></div><div className="field"><label>To</label><input className="input" type="date" value={filters.end_date} onChange={e=>set("end_date",e.target.value)}/></div><div className="field"><label>Account</label><select className="select" value={filters.account_id} onChange={e=>set("account_id",e.target.value)}><option value="">All</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="field"><label>Category</label><select className="select" value={filters.category_id} onChange={e=>set("category_id",e.target.value)}><option value="">All</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Type</label><select className="select" value={filters.transaction_type} onChange={e=>set("transaction_type",e.target.value)}><option value="">All</option>{["expense","income","transfer","credit_card_payment","refund","fee","adjustment","other"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></div></div>
 <div className="card table-card">{!rows.length?<EmptyState title="No matching transactions" body="Confirmed imports appear here. Try clearing filters or import a CSV."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Description</th><th>Account</th><th>Category</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map(row=>{const account=accounts.find(a=>a.id===row.account_id);return <tr key={row.id} className={row.is_excluded_from_spending?"excluded-row":""}><td>{shortDate(row.transaction_date)}</td><td><strong>{row.merchant_name||row.description_clean}</strong>{row.merchant_name&&<div className="muted">{row.description_clean}</div>}</td><td>{account?.name||"—"}{row.card_last_four&&<div className="muted">Card {row.card_last_four}</div>}</td><td><select className="select" value={row.category_id||""} onChange={e=>change(row,{category_id:e.target.value||null,subcategory_id:null})}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td><select className="select" value={row.transaction_type} onChange={e=>change(row,{transaction_type:e.target.value})}>{["expense","income","transfer","credit_card_payment","refund","fee","adjustment","other"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></td><td className={`amount ${row.direction}`}>{row.direction==="inflow"?"+":"−"}{money(row.amount)}</td><td><div className="flag-stack">{row.is_excluded_from_spending&&<Badge>excluded</Badge>}{row.is_recurring&&<Badge tone="good">recurring</Badge>}{!row.category_id&&<Badge tone="warn">review</Badge>}</div></td></tr>})}</tbody></table></div>}</div>
 </>;
}

