"use client";
import { FormEvent, useEffect, useState } from "react";
import { Plus, X } from "lucide-react";
import { Badge, EmptyState, PageHeader } from "@/components/Page";
import { api } from "@/lib/api";
import type { Account, Instrument } from "@/lib/types";

export default function AccountsPage() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [instruments, setInstruments] = useState<Record<string,Instrument[]>>({}); const [modal, setModal] = useState<"account"|"instrument"|null>(null); const [selected, setSelected] = useState<string>(""); const [error, setError] = useState("");
  async function load() { const rows = await api<Account[]>("/accounts"); setAccounts(rows); const pairs = await Promise.all(rows.map(async (row) => [row.id, await api<Instrument[]>(`/accounts/${row.id}/instruments`)] as const)); setInstruments(Object.fromEntries(pairs)); }
  useEffect(() => { load(); }, []);
  async function addAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await api("/accounts", {method:"POST", body:JSON.stringify({name:f.get("name"),provider_name:f.get("provider")||null,account_type:f.get("type"),last_four:f.get("last_four")||null,currency:"USD",statement_cycle_day:f.get("cycle") ? Number(f.get("cycle")):null,payment_due_day:f.get("due")?Number(f.get("due")):null})}); setModal(null); await load(); } catch(e){setError(e instanceof Error?e.message:"Could not save");} }
  async function addInstrument(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await api(`/accounts/${selected}/instruments`, {method:"POST", body:JSON.stringify({instrument_type:f.get("type"),display_name:f.get("name"),cardholder_name:f.get("holder")||null,last_four:f.get("last_four")||null,source_identifier:f.get("last_four")?`xxxx${f.get("last_four")}`:null})}); setModal(null); await load(); } catch(e){setError(e instanceof Error?e.message:"Could not save");} }
  async function disable(id:string){ await api(`/accounts/${id}`,{method:"DELETE"}); await load(); }
  async function editAccount(item:Account){const name=window.prompt("Account name",item.name);if(!name)return;const provider=window.prompt("Provider name",item.provider_name||"");await api(`/accounts/${item.id}`,{method:"PATCH",body:JSON.stringify({name,provider_name:provider||null})});await load()}
  async function editInstrument(item:Instrument){const display_name=window.prompt("Card/profile display name",item.display_name);if(!display_name)return;const cardholder_name=window.prompt("Cardholder name",item.cardholder_name||"");await api(`/account-instruments/${item.id}`,{method:"PATCH",body:JSON.stringify({display_name,cardholder_name:cardholder_name||null})});await load()}
  async function disableInstrument(item:Instrument){await api(`/account-instruments/${item.id}`,{method:"DELETE"});await load()}
  return <><PageHeader eyebrow="Financial accounts" title="Accounts & cards" description="Keep statement accounts as parents. Add physical cards and authorized users beneath them for attribution." actions={<button className="button button-primary" onClick={()=>setModal("account")}><Plus size={16}/>Add account</button>}/>
    {!accounts.length ? <div className="card"><EmptyState title="Add your first account" body="Create a checking, savings, cash, or credit card account before importing transactions." action={<button className="button button-primary" onClick={()=>setModal("account")}>Add account</button>}/></div> : <div className="grid grid-3">{accounts.map((item)=><div className="card account-card" key={item.id}><div className="account-head"><div><h3>{item.name}</h3><span className="account-meta">{item.provider_name || "No provider"}{item.last_four && ` · •••• ${item.last_four}`}</span></div><Badge tone={item.is_active?"good":"neutral"}>{item.account_type.replaceAll("_"," ")}</Badge></div><div className="instrument-list">{(instruments[item.id]||[]).map((instrument)=><div className="instrument-row" key={instrument.id}><span>{instrument.display_name}{instrument.last_four&&` · ${instrument.last_four}`}</span><span className="page-actions">{!instrument.is_active&&<Badge>disabled</Badge>}<button className="icon-button" onClick={()=>editInstrument(instrument)}>Edit</button>{instrument.is_active&&<button className="icon-button danger" onClick={()=>disableInstrument(instrument)}>Disable</button>}</span></div>)}<button className="button" onClick={()=>{setSelected(item.id);setModal("instrument")}}><Plus size={14}/>Add card/profile</button><button className="button" onClick={()=>editAccount(item)}>Edit account</button>{item.is_active&&<button className="button button-danger" onClick={()=>disable(item.id)}>Disable account</button>}</div></div>)}</div>}
    {modal&&<div className="modal-backdrop"><div className="modal"><div className="modal-header"><h2>{modal==="account"?"Add financial account":"Add card or profile"}</h2><button className="icon-button" onClick={()=>setModal(null)}><X/></button></div>{error&&<div className="notice notice-error">{error}</div>}{modal==="account"?<form onSubmit={addAccount}><div className="form-grid"><div className="field full"><label>Account name</label><input className="input" name="name" placeholder="Chase Sapphire Preferred" required/></div><div className="field"><label>Provider</label><input className="input" name="provider" placeholder="Chase"/></div><div className="field"><label>Account type</label><select className="select" name="type" defaultValue="checking"><option value="checking">Checking</option><option value="savings">Savings</option><option value="credit_card">Credit card</option><option value="cash">Cash</option><option value="other">Other</option></select></div><div className="field"><label>Last four (optional)</label><input className="input" name="last_four" pattern="[0-9]{4}" maxLength={4}/></div><div className="field"><label>Statement cycle day</label><input className="input" type="number" name="cycle" min={1} max={31}/></div><div className="field"><label>Payment due day</label><input className="input" type="number" name="due" min={1} max={31}/></div></div><div className="form-actions"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button button-primary">Save account</button></div></form>:<form onSubmit={addInstrument}><div className="form-grid"><div className="field full"><label>Display name</label><input className="input" name="name" placeholder="Spouse card ending 5678" required/></div><div className="field"><label>Type</label><select className="select" name="type"><option value="credit_card">Credit card</option><option value="authorized_user_card">Authorized user card</option><option value="debit_card">Debit card</option><option value="other">Other</option></select></div><div className="field"><label>Cardholder</label><input className="input" name="holder"/></div><div className="field"><label>Last four</label><input className="input" name="last_four" pattern="[0-9]{4}" maxLength={4}/></div></div><div className="form-actions"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button button-primary">Save profile</button></div></form>}</div></div>}
  </>;
}
