"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, UploadCloud } from "lucide-react";
import { Badge, EmptyState, PageHeader } from "@/components/Page";
import { api, shortDate } from "@/lib/api";
import type { Account, ImportRecord } from "@/lib/types";

interface SavedMapping { id:string; mapping_name:string; provider_name:string; account_type:string; amount_behavior:string; updated_at:string; }

export default function ImportsPage() {
  const router=useRouter(); const [accounts,setAccounts]=useState<Account[]>([]); const [imports,setImports]=useState<ImportRecord[]>([]); const [mappings,setMappings]=useState<SavedMapping[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){const [a,i,m]=await Promise.all([api<Account[]>("/accounts"),api<ImportRecord[]>("/imports"),api<SavedMapping[]>("/mappings")]);setAccounts(a.filter(x=>x.is_active));setImports(i);setMappings(m)}
  useEffect(()=>{load();},[]);
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const result=await api<ImportRecord>("/imports/upload",{method:"POST",body:form});router.push(`/imports/${result.id}/mapping`);}catch(e){setError(e instanceof Error?e.message:"Upload failed");setBusy(false)}}
  function destination(item:ImportRecord){return item.status==="review_pending"?`/imports/${item.id}/review`:`/imports/${item.id}/mapping`;}
  async function editMapping(mapping:SavedMapping){const name=window.prompt("Mapping name",mapping.mapping_name);if(!name)return;const provider=window.prompt("Provider name",mapping.provider_name);if(!provider)return;await api(`/mappings/${mapping.id}`,{method:"PATCH",body:JSON.stringify({mapping_name:name,provider_name:provider})});await load()}
  async function deleteMapping(mapping:SavedMapping){if(!window.confirm(`Delete saved mapping “${mapping.mapping_name}”?`))return;await api(`/mappings/${mapping.id}`,{method:"DELETE"});await load()}
  return <><PageHeader eyebrow="Import workspace" title="Bring in transactions" description="Upload a bank or card CSV. Every row stays in draft until you review and confirm it."/>
    <div className="grid grid-2"><div className="card card-pad"><h2>Upload CSV</h2>{error&&<div className="notice notice-error">{error}</div>}{!accounts.length?<EmptyState title="An account comes first" body="Add the parent financial account that owns these transactions before uploading." action={<Link href="/accounts" className="button button-primary">Go to accounts</Link>}/>:<form onSubmit={upload}><div className="field"><label>Destination account</label><select className="select" name="account_id" required><option value="">Choose an account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="upload-zone" style={{marginTop:16}}><UploadCloud size={35}/><strong>Choose a CSV export</strong><p>Up to 25 MB. The original file stays on this computer.</p><input name="file" type="file" accept=".csv,text/csv" required/><button className="button button-primary" disabled={busy}>{busy?"Reading file…":"Upload and inspect"}</button></div></form>}</div>
    <div><div className="section-title" style={{marginTop:0}}><div><h2>Import history</h2><p>Resume drafts at any time</p></div></div><div className="card table-card">{!imports.length?<EmptyState title="No imports yet" body="Your uploads and unfinished reviews will appear here."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>File</th><th>Status</th><th>Rows</th><th></th></tr></thead><tbody>{imports.map(item=><tr key={item.id}><td><strong>{item.original_filename}</strong><div className="muted">{shortDate(item.created_at)}{item.provider_name&&` · ${item.provider_name}`}</div></td><td><Badge tone={item.status==="confirmed"?"good":item.status==="failed"?"danger":"warn"}>{item.status.replaceAll("_"," ")}</Badge></td><td>{item.row_count}{item.duplicate_row_count>0&&<div className="danger">{item.duplicate_row_count} duplicate</div>}</td><td>{!["confirmed","cancelled"].includes(item.status)&&<Link className="icon-button" href={destination(item)}><ArrowRight size={18}/></Link>}</td></tr>)}</tbody></table></div>}</div></div></div>
    <div className="section-title"><div><h2>Saved provider mappings</h2><p>Header-signature mappings reused by future uploads</p></div></div><div className="card table-card"><div className="table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Provider</th><th>Account type</th><th>Amount behavior</th><th>Actions</th></tr></thead><tbody>{mappings.length?mappings.map(mapping=><tr key={mapping.id}><td><strong>{mapping.mapping_name}</strong></td><td>{mapping.provider_name}</td><td>{mapping.account_type.replaceAll("_"," ")}</td><td>{mapping.amount_behavior.replaceAll("_"," ")}</td><td><div className="page-actions"><button className="button" onClick={()=>editMapping(mapping)}>Edit</button><button className="button button-danger" onClick={()=>deleteMapping(mapping)}>Delete</button></div></td></tr>):<tr><td colSpan={5} className="muted">Mappings appear after a column mapping is confirmed.</td></tr>}</tbody></table></div></div>
  </>;
}
